### ISSUE TITLE
Copying files with new extension, not replacing the extension

### ISSUE THREAD

**Issue by autopulous** [tjeastmond/gulp-ext-replace#10]
The following code is copying `.css` files as `.css.hidden` (not renaming)

```
gulp.task('hide-material-css-files', function () {
    var ext_replace = require('gulp-ext-replace');

    console.log(ext_replace);

    return gulp.src(material + '/**/*.css')
               .pipe(ext_replace('.css.hidden'))
               .pipe(gulp.dest(material));
});
```
is there a way to get the function to rename instead of copying?

**Comment by autopulous** [comment]
After further review: all gulp-ext-replace does is manipulate the file name and the gulp.dest() does the work of creating the new file...

**Comment by autopulous** [comment]
It would be nice if the documentation mentioned that the function simply creates a new name for the file and it is up to the consumer of the the new filename to perform the appropriate read/write actions...

**Comment by tjeastmond** [comment]
You'll find that most gulp extension don't overwrite a file. They idea is to compile and/or output files to the build directory.

Extensions should do only one thing. If they are doing more than one, they're doing it wrong.
