### ISSUE TITLE
Rename files which have multiple extension type such as *.haml.html to *.html

### ISSUE THREAD

**Issue by AndreyAntipov** [tjeastmond/gulp-ext-replace#4]
Hello

I'm using rails style file format. So, it's look like `index.haml.html`
Would be a nice to have option for working with files which have multiple types. 

*Example:*
Origin file `index.haml.html` or `index.html`or `index.haml.something.html`  → `index.html`

Can i send a pull request for this missing feature?

**Comment by tjeastmond** [comment]
Fixed in latest update. See README
